### ISSUE TITLE
Where is the tes3mp-client-default.cfg file?

### ISSUE THREAD

**Issue by Albacksen** [TES3MP/server-docker#7]
Sorry if this is a silly question. But is there an easy way to get the docker to read changes to the **tes3mp-client-default.cfg** file? 

Most dockers I've seen have either instructions on that part, or Enviroment Variables to help you set certain things inside the volume, pre-launch.

**Comment by GrimKriegor** [comment]
Hey there.

`tes3mp-client-default.cfg` is in `/server/tes3mp-client-default.cfg` the WORKDIR of that container image.
Up until now the only way to get changes to stick in that file would be to mount it as a volume.
But this latest change might interest you:
https://github.com/TES3MP/server-docker/commit/9b5429f10e8b60ff790786eadcb46c31cd5e2b3f

A bit of a hacky trick, but it should suffice for now.
On startup, the container will look for any environment variables prefixed by `TES3MP_SERVER_` and change the config file accordingly.

Things like `TES3MP_SERVER_MAXIMUM_PLAYERS=12` will become `maximumPlayers = 12`.

Container image has been updated with this. Give it try!

```
docker run --rm -it \
    --name TES3MP-server \
    -e TES3MP_SERVER_HOSTNAME="C0da Enjoyers Server" \
    -e TES3MP_SERVER_MAXIMUM_PLAYERS=1 \
    -e TES3MP_SERVER_PASSWORD="superExclusive" \
    -p "25565:25565/udp" \
    tes3mp/server
```

**Comment by Albacksen** [comment]
That worked great! I added the volume argument back in, since I noticed it was missing after running it and being brought back to chargen. :P
Might be an idea to add the evars to the description so scrubs like me prior to posting this know it's an option now.

**Comment by GrimKriegor** [comment]
Excellent news!
Documentation on the feature has been added [alongside it](https://github.com/TES3MP/server-docker#configuration), thats why you didn´t find it at the time.
Good luck.
