### ISSUE TITLE
Version mismatch with 0.8.0 Client

### ISSUE THREAD

**Issue by karelmous** [TES3MP/server-docker#8]
First of all, thank for the great work! Am thoroughly enjoying running a private TES3MP server in a Docker container.

Installed TES3MP via the Docker Hub Registry. The version in the registry is version 0.7.0, while the latest available downloadable client is version 0.8.0. Will the Docker Hub Registry eventually be updated to version 0.8.0 as well?

**Comment by Lowdude** [comment]
It seems that this was more or less done in February, but some check failed (?) so the dockerhub image has not been updated. I would really appreciate a fix as well, it is such a convenient container to have.

**Comment by GrimKriegor** [comment]
Hello there.
Images for 0.8.0 and 0.8.1 are now available.
Thank you for your patience.

Fixed by b3bd5af577eb5f34f0347248e97eb40545b633ef

**Comment by karelmous** [comment]
Thanks so much for updating the Docker Image. It's up and running at my server!
